### ISSUE TITLE
Error message when opening Anki related to this add-on

### ISSUE THREAD

**Issue by dollajas** [AnKing-Memberships/AnKing-Note-Types#137]
#### Which Note Type (and version) is this about?
2.1.62 Qt6 intel mac

#### Problem description

Anytime I open Anki or the tooltip I get this error:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.3.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-04-30 13:09:34
Add-ons possibly involved: ⁨AnKing Note Types Easy Customization⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 217, in on_window_init
  File "aqt.main", line 316, in setupProfile
  File "aqt.main", line 496, in loadProfile
  File "_aqt.hooks", line 3809, in __call__
  File "/Users/abdullajastaniah/Library/Application Support/Anki2/addons21/952691989/__init__.py", line 36, in on_profile_did_open
    maybe_show_notetypes_update_notice()
  File "/Users/abdullajastaniah/Library/Application Support/Anki2/addons21/952691989/__init__.py", line 63, in maybe_show_notetypes_update_notice
    models_with_updates = models_with_available_updates()
  File "/Users/abdullajastaniah/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py", line 558, in models_with_available_updates
    return [
  File "/Users/abdullajastaniah/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py", line 562, in <listcomp>
    if _new_version_available_for_model(model)
  File "/Users/abdullajastaniah/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py", line 569, in _new_version_available_for_model
    newest_version = note_type_version(anking_notetype_model(base_name))
  File "/Users/abdullajastaniah/Library/Application Support/Anki2/addons21/952691989/notetype_setting_definitions.py", line 595, in anking_notetype_model
    (ANKING_NOTETYPES_PATH / notetype_name / f"{notetype_name}.json").read_text()
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

**Comment by dollajas** [comment]
Please ignore
